<template>
   <div class="pages-content"><h2>Jive Software</h2><br><p>Worked on jivesoftware.com and other Jive properties while consistently incorporating new ideas via the Marketing department. Coded in heavily customized Wordpress builds that utilized custom post types, child themes, custom fields (ACF). Wrote PHP loops, functions, ternary expressions and conditional statements in creating templates from scratch, feeding data and generating logic. Wrote Javascript functions and data storage objects to facilitate translation of Marketo form fields to various foreign languages depending on visitor's geographic location.</p><br><br><h2>Empirical UX</h2><br><p>Built UI components and interactions using AngularJS for data-intensive apps used by Intel and Jaguar. Used services and dependency injection to share data models. Migrated several areas of code from jQuery to Angular. Made calls to Intel back-end codebase using http service. Used existing Angular directives to loop through data to build out UI. Created custom directives that corresponded to specific areas of the application and its respective data.</p><br><br><h2>WebLively</h2><br><p>Responsible for converting landing pages to responsive, mobile-friendly designs. Used Bootstrap grid and custom media queries. Coded in Less and compiled to CSS. Designed and implemented modernizing style updates with input from stakeholders. Worked in CodeIgniter codebase writing both PHP and JS. Acted with CEO to construct overall UX strategy.</p><br><br><h2>Unigo Group</h2><br><p>Co-created and maintained &#8203;corporate blog&#8203; following brand guidelines using Foundation 5 and Wordpress. Used Sass to add features and modify styling in Unigo.com code-base. Designed email template mock-ups in collaboration with marketing department. Gained further exposure to .Net, Visual Studio, version control, agile development, and task management tools (Jira, etc.). </p><br><br><h2>Switchboard</h2><br><p>Helped to create internal metrics dashboard using front-end MVC framework with dynamic data populated through RESTful API calls. &#8203; Constructed Rails application to serve FAQs to users, incorporating a CMS-style interface for non-technical admins.&#8203; Utilized Javascript to create scrolling and show/hide functionality. &#8203; Pushed other new site features such as &#8203;Javascript tool-tips, site-wide alerts, &#8203;contextual pop-ups and email preview functionality to code-base.</p><a class="hvr-shutter-in-horizontal page-button v-link-active" href="/">Home</a></div>

      
</template>

<style scope>
  .work{
    color: Red
  }
</style>